"""Exception hierarchy. Nothing in the system swallows these silently."""


class PMError(Exception):
    """Base class for all project-manager errors."""


class ConfigError(PMError): ...
class DocumentError(PMError): ...
class OllamaUnavailableError(PMError): ...
class ModelUnavailableError(PMError): ...
class LLMError(PMError): ...
class LLMTimeoutError(LLMError): ...
class AgentOutputError(PMError):
    """Agent returned unparsable JSON or JSON that violates its schema."""
class StateUpdateError(PMError):
    """Agent output parsed fine but cannot be safely merged into the canonical state."""
class AgentFailure(PMError):
    """An agent step failed after all retries."""
class OrchestrationError(PMError): ...
